<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Camera' => '',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Desktops' => '',
    'Display in top menu' => 'Показывать в верхнем меню',
    'Invalid product category' => 'Неправильная категория',
    'Laptops & Notebooks' => '',
    'Manage Product Categories' => 'Управление категориями товаров',
    'Product Categories' => 'Категории товаров',
    'Product Category' => 'Категория товаров',
    'Shop Camera feature only the best laptop deals on the market' => '',
    'Shop Desktop feature only the best desktop deals on the market' => '',
    'Shop Laptop feature only the best laptop deals on the market' => '',
    'Show' => 'Показать',
    'camera' => '',
    'desktops' => '',
    'laptops-notebooks' => '',
];
